/*
const initialPieces = [
    { type: "rook", colour: "black", row: 0, col: 0 },
    { type: "knight", colour: "black", row: 0, col: 1 },
    { type: "bishop", colour: "black", row: 0, col: 2 },
    { type: "queen", colour: "black", row: 0, col: 3 },
    { type: "king", colour: "black", row: 0, col: 4 },
    { type: "bishop", colour: "black", row: 0, col: 5 },
    { type: "knight", colour: "black", row: 0, col: 6 },
    { type: "rook", colour: "black", row: 0, col: 7 },
    { type: "pawn", colour: "black", row: 1, col: 0 },
    { type: "pawn", colour: "black", row: 1, col: 1 },
    { type: "pawn", colour: "black", row: 1, col: 2 },
    { type: "pawn", colour: "black", row: 1, col: 3 },
    { type: "pawn", colour: "black", row: 1, col: 4 },
    { type: "pawn", colour: "black", row: 1, col: 5 },
    { type: "pawn", colour: "black", row: 1, col: 6 },
    { type: "pawn", colour: "black", row: 1, col: 7 },
    { type: "pawn", colour: "white", row: 6, col: 0 },
    { type: "pawn", colour: "white", row: 6, col: 1 },
    { type: "pawn", colour: "white", row: 6, col: 2 },
    { type: "pawn", colour: "white", row: 6, col: 3 },
    { type: "pawn", colour: "white", row: 6, col: 4 },
    { type: "pawn", colour: "white", row: 6, col: 5 },
    { type: "pawn", colour: "white", row: 6, col: 6 },
    { type: "pawn", colour: "white", row: 6, col: 7 },
    { type: "rook", colour: "white", row: 7, col: 0 },
    { type: "knight", colour: "white", row: 7, col: 1 },
    { type: "bishop", colour: "white", row: 7, col: 2 },
    { type: "queen", colour: "white", row: 7, col: 3 },
    { type: "king", colour: "white", row: 7, col: 4 },
    { type: "bishop", colour: "white", row: 7, col: 5 },
    { type: "knight", colour: "white", row: 7, col: 6 },
    { type: "rook", colour: "white", row: 7, col: 7 }
];
*/

const initialPieces = [
    { type: "rook", colour: "black", row: 0, col: 0 },
    { type: "knight", colour: "black", row: 0, col: 1 },
    { type: "bishop", colour: "black", row: 0, col: 2 },
    { type: "queen", colour: "black", row: 0, col: 3 },
    { type: "king", colour: "black", row: 0, col: 4 },
    { type: "bishop", colour: "black", row: 0, col: 5 },
    { type: "knight", colour: "black", row: 0, col: 6 },
    { type: "rook", colour: "black", row: 0, col: 7 },
    { type: "pawn", colour: "black", row: 1, col: 0 },
    { type: "pawn", colour: "black", row: 1, col: 1 },
    { type: "pawn", colour: "black", row: 1, col: 2 },
    { type: "pawn", colour: "black", row: 1, col: 3 },
    { type: "pawn", colour: "black", row: 1, col: 4 },
    { type: "pawn", colour: "black", row: 1, col: 5 },
    { type: "pawn", colour: "black", row: 1, col: 6 },
    { type: "pawn", colour: "black", row: 1, col: 7 },
    { type: "pawn", colour: "white", row: 6, col: 0 },
    { type: "pawn", colour: "white", row: 6, col: 1 },
    { type: "pawn", colour: "white", row: 6, col: 2 },
    { type: "pawn", colour: "white", row: 6, col: 3 },
    { type: "pawn", colour: "white", row: 6, col: 4 },
    { type: "pawn", colour: "white", row: 6, col: 5 },
    { type: "pawn", colour: "white", row: 6, col: 6 },
    { type: "pawn", colour: "white", row: 6, col: 7 },
    { type: "rook", colour: "white", row: 7, col: 0 },
    { type: "knight", colour: "white", row: 7, col: 1 },
    { type: "bishop", colour: "white", row: 7, col: 2 },
    { type: "queen", colour: "white", row: 7, col: 3 },
    { type: "king", colour: "white", row: 7, col: 4 },
    { type: "bishop", colour: "white", row: 7, col: 5 },
    { type: "knight", colour: "white", row: 7, col: 6 },
    { type: "rook", colour: "white", row: 7, col: 7 }
];

export {initialPieces};